name = "taka-worker"
main = "src/index.ts"
compatibility_date = "2023-01-23"
kv_namespaces = [
  { binding = "MY_KV", id = "f488b9efda624880bdf24597394dcafa" }
]
r2_buckets = [
  { binding = "MY_BUCKET", bucket_name = "takabucket", preview_bucket_name = "" }
]
